apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/yohoom/sprint-boot-rest-prometheus:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/yohoom/sprint-boot-rest-prometheus:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: sprint-boot-rest-prometheus
        chartPath: charts/sprint-boot-rest-prometheus
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/yohoom/sprint-boot-rest-prometheus'
          image.tag: '{{.DIGEST_HEX}}'
